### PR TITLE
Handled list secrets for no secret in namespaces

### LINKED ISSUE #220: Secret listing does not handle the empty namespace gracefully
## Expected Behaviour

Running the `GetSecretList` shouold return an empty list when the namespace exists, is valid, but has not yet create the secrets mount folder

## Current Behaviour

Running the certifier with multiple namespaces enabled produces an error at the beginning of the secrets CRUD tests

```
secretCRUD_test.go:78: server returned unexpected status code: 500 - open /var/lib/faasd-provider/secrets/certifier-test: no such file or directory
```

Which comes from  this snippet of code

```go
secrets, err := config.Client.GetSecretList(ctx, tc.secret.Namespace)
if err != nil {
    t.Fatal(err)
}
```

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [x] Yes
- [ ] No

## List all Possible Solutions

The `listSecrets` merthod should check if the path exists before attempting to use `ReadDir`. If the directory does not exist, it should return the empty list.

https://github.com/openfaas/faasd/blob/acb5d0bd1cc5876d05261857b0717b779b95ec1b/pkg/provider/handlers/secret.go#L49-L79

## List the one solution that you would recommend

^ that one

## Steps to Reproduce (for bugs)

1. Install faasd in multipass using https://github.com/openfaas/faasd/pull/219
2. Once it is started, ssh into the VM and create the test namespace using 
    ```sh
    sudo ctr namespace create certifier-test
    sudo ctr namespace label certifier-test openfaas=true
    ```
3. On your local machine, clone the certifier https://github.com/openfaas/certifier
4. Run the faasd tests using `make test-faasd`

## Context

This is blocking the completely of the certifier

### PR DESCRIPTION
**Pull request by nitishkumar71**
Signed-off-by: Nitishkumar Singh <nitishkumarsingh71@gmail.com>

FIxes the list secret issue for namespace with no secret
## Description

The current faasd implementation included bug due to which, we receive error while listing secrets for any namespace which don't have any secret created.
## Motivation and Context

- [x] I have raised an issue to propose this change **this is required**
Resolve #220 

## How Has This Been Tested?

1. Build and deploy the local binary
2. Create a new namespace
```
sudo ctr namespace create test-ns
sudo ctr namespace label test-ns openfaas=true
```
3. List secrets using faas-cli, which provides output `No secrets found.`
```
faas-cli secret ls --namespace openfaas-fn
faas-cli secret ls --namespace test-ns
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Commits:

- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] My commit message has a body and describe how this was tested and why it is required.
- [x] I have signed-off my commits with `git commit -s` for the Developer Certificate of Origin (DCO)

Code:

- [x] My code follows the code style of this project.
- [x] I have added tests to cover my changes.

Docs:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: pkg/provider/handlers/secret_test.go [hunk 1]
```diff
@@ -161,3 +163,69 @@ func TestSecretCreation(t *testing.T) {
...
+			status:     http.StatusOK,
+			secretPath: "/test-fn/foo",
+			secret:     "bar",
+			expected:   make([]types.Secret, 0),
+		},
+	}
+
+	for _, tc := range cases {
+		t.Run(tc.name, func(t *testing.T) {
+			req := httptest.NewRequest(tc.verb, "http://example.com/foo", strings.NewReader(""))
```
Comment (LucasRoesler) [inline pkg/provider/handlers/secret_test.go:198]: I think a `nil` body is allowed here and mimics the GET request better

File: pkg/provider/handlers/secret_test.go [hunk 2]
```diff
@@ -161,3 +163,69 @@ func TestSecretCreation(t *testing.T) {
...
+		status     int
+		secretPath string
+		secret     string
+		err        string
+		expected   []types.Secret
+	}{
+		{
+			name:       "Get empty secret list for namespace having no secret",
+			verb:       http.MethodGet,
+			status:     http.StatusOK,
```
Comment (LucasRoesler) [inline pkg/provider/handlers/secret_test.go:189]: The test case doesn't account for the non-default namespace, i think it needs another field `namespace` to accurately test the bug I saw. This first case is fine, it represents the default namespace, but it seems like we need a second case for a non-default namespace.  If i recall correctly, it should be as simple as adding `"?namespace="+tc.namespace` to the url _if_ `tc.namespace` is not empty.

**Review by LucasRoesler — CHANGES_REQUESTED** [review]

File: pkg/provider/handlers/secret_test.go (hunk 1 above)
Comment (nitishkumar71) [reply pkg/provider/handlers/secret_test.go]: Thanks for feedback.

File: pkg/provider/handlers/secret_test.go (hunk 2 above)
Comment (nitishkumar71) [reply pkg/provider/handlers/secret_test.go:189]: I could not find any example to mock containerd client. `listSecrets` method calls `validNamespace` method, which need uses containerd client.

https://github.com/openfaas/faasd/blob/acb5d0bd1cc5876d05261857b0717b779b95ec1b/pkg/provider/handlers/secret.go#L53

File: pkg/provider/handlers/secret_test.go [hunk 3]
```diff
@@ -161,3 +163,69 @@ func TestSecretCreation(t *testing.T) {
...
+
+func TestListSecrets(t *testing.T) {
+	mountPath, err := os.MkdirTemp("", "test_secret_creation")
+	if err != nil {
+		t.Fatalf("unexpected error while creating temp directory: %s", err)
+	}
+
+	defer os.RemoveAll(mountPath)
+
+	handler := MakeSecretHandler(nil, mountPath)
```
Comment (alexellis) [inline pkg/provider/handlers/secret_test.go:175]: You could create an interface named "NamespaceChecker" which has a single method. This would have a fake version for unit testing and a real version with a reference to the client.

Comment (alexellis) [reply pkg/provider/handlers/secret_test.go:175]: Another idea might be to try using the Store interface from containerd, and then only pass in the namespace store: https://github.com/openfaas/faasd/blob/acb5d0bd1cc5876d05261857b0717b779b95ec1b/vendor/github.com/containerd/containerd/namespaces/store.go#L29

File: pkg/provider/handlers/secret_test.go (hunk 2 above)
Comment (nitishkumar71) [reply pkg/provider/handlers/secret_test.go:192]: @LucasRoesler Have made the changes as per comment in test.

File: pkg/provider/handlers/secret_test.go (hunk 3 above)
Comment (nitishkumar71) [reply pkg/provider/handlers/secret_test.go]: Thanks for the suggestion, have implemented the first approach

File: pkg/provider/handlers/secret.go [hunk 4]
```diff
@@ -10,14 +10,14 @@ import (
...
-	"github.com/containerd/containerd"
 	"github.com/openfaas/faas-provider/types"
+	wrapper "github.com/openfaas/faasd/pkg/provider"
 )
 
 const secretFilePermission = 0644
 const secretDirPermission = 0755
 
-func MakeSecretHandler(c *containerd.Client, mountPath string) func(w http.ResponseWriter, r *http.Request) {
+func MakeSecretHandler(c wrapper.ClientInterface, mountPath string) func(w http.ResponseWriter, r *http.Request) {
```
Comment (LucasRoesler) [inline pkg/provider/handlers/secret.go:20]: This is the right approach but i think we could simplify it. There are two alternatives. I think option (1) is preferred

1. Directly passing the `namespaces.Store` interface. 
    
    ```suggestion
    func MakeSecretHandler(c namespaces.Store, mountPath string) func(w http.ResponseWriter, r *http.Request) {
    ```
    
    The wrapper only provides a method to get the NamespaceService without any other actions or behavior, so it isn't clear we gain a lot.
    
    You can go even further and use a custom interface 
    
    ```go
    type Labeller interface {
       Labels(ctx context.Context, namespace string) (map[string]string, error)
    }
    ```

2. Or go even one step further and just pass a function (because Go has first-class functions)
    
    ```go 
    type GetLabels = func(ctx context.Context, namespace string) (map[string]string, error)
    ```
    
    
    Which would make this handler factory look like this
    
    ```go
    type GetLabels = func(ctx context.Context, namespace string) (map[string]string, error)
    
    func MakeSecretHandler(getLabels GetLabels, mountPath string) func(w http.ResponseWriter, r *http.Request) {
    ```
    
    and the provider initialization would look like
    
    ```go
    SecretHandler: handlers.MakeSecretHandler(client.NamespaceService().Labels, baseUserSecretsPath),
    ```


Option (2) is good if you are very confident that you won't need additional methods in the future. Option (1) is slightly more flexible because we can expand the client interface in the future with exactly the methods we need, and no more than that. I also think (1) reads more cleanly too.

**Review by LucasRoesler — CHANGES_REQUESTED** [review]
@nitishkumar71 just one comment about the wrapper interface you added. I think we can simplify it a little bit. But otherwise, it looks good and the approach is :+1: :+1:

File: pkg/provider/handlers/secret.go (hunk 4 above)
Comment (nitishkumar71) [reply pkg/provider/handlers/secret.go:20]: I too have thought to use option 1 for implementation. But the issue testing issue which we faced for this can also occur in other handlers too which are using other containerd client methods. We can use the same `ClientInterface` to do the mock for other handlers too in future.

**Comment by nitishkumar71** [comment]
> think
@LucasRoesler Please do let me know your thoughts on the comment.

File: pkg/provider/handlers/secret.go (hunk 4 above)
Comment (LucasRoesler) [reply pkg/provider/handlers/secret.go:20]: I think the general philosophy is that smaller local interfaces are better. 

So, it is ok to have a very narrow interface here that only this handler requires (and the containerd namespaces client implements) and then a separate interface for the other handlers. 

The smaller your interface, the easier it is to mock or replace with a new implementation. If the interface is "every containerd method we use in the whole app" then it is harder to extend because your new implementation for a single handler needs all of those methods.

Comment (nitishkumar71) [reply pkg/provider/handlers/secret.go]: Thank you so much, it makes it clear. I have done the changes requested.

**Review by LucasRoesler — APPROVED** [review]

**Comment by nitishkumar71** [comment]
@alexellis Please do review when you get time.

File: pkg/provider/mock.go [hunk 5]
```diff
@@ -0,0 +1,16 @@
+package provider
+
+import (
+	"context"
+)
+
+type MockStore struct {
```
Comment (alexellis) [inline pkg/provider/mock.go:7]: Could we get a title on the MockStore struct?

File: pkg/provider/interface.go [hunk 6]
```diff
@@ -0,0 +1,7 @@
+package provider
```
Comment (alexellis) [inline pkg/provider/interface.go:1]: What about a file called labeller.go with both in?

File: pkg/provider/handlers/secret_test.go [hunk 7]
```diff
@@ -161,3 +166,93 @@ func TestSecretCreation(t *testing.T) {
...
+			labels: map[string]string{
+				pkg.NamespaceLabel: "true",
+			},
+		},
+	}
+
+	for _, tc := range cases {
+		t.Run(tc.name, func(t *testing.T) {
+			fakeStore := &mock.MockStore{
+				FakeLabels: func() (map[string]string, error) {
```
Comment (alexellis) [inline pkg/provider/handlers/secret_test.go:214]:
```go
type FakeStore struct {
  Labels map[string]string
}

func (s *MockStore) Labels(ctx context.Context, namespace string) (map[string]string, error) {
        return s.Labels, nil
}


fs:= FakeStore{}
fs.Labels = tc.labels

```

Comment (nitishkumar71) [reply pkg/provider/handlers/secret_test.go]: Changes are done.

File: pkg/provider/mock.go (hunk 5 above)
Comment (nitishkumar71) [reply pkg/provider/mock.go]: Changes are done.

File: pkg/provider/interface.go (hunk 6 above)
Comment (nitishkumar71) [reply pkg/provider/interface.go]: Done

**Comment by alexellis** [comment]
Please have a look at this changeset to see another couple of things I did: https://github.com/openfaas/faasd/commit/8003748b733e8caf40d61dea4bc36952d16f109c

1) changed the comment format
2) changed "expected" terminology which is about BDD and assertion libraries to idiomatic Go i.e. want/got
3) added a "new" function for the fake labeller and renamed "FakeLabels" to "labels" and made it private for encapsulation. This function returns the actual interface instead of the concrete type

Good work on this PR from you :+1:
